:recycle: :sparkles: Fixes, moves and corrections

diff --git a/src/bin/pushover b/src/bin/pushover
--- a/src/bin/pushover
+++ b/src/bin/pushover
@@ -1,14 +1,14 @@
-#!/bin/bash
+#!/bin/sh
 
-if [[ -z "${PUSH_OVER_TOKEN}" || -z "${PUSH_OVER_USER}" ]]; then
-  echo "Required credentials <PUSH_OVER_TOKEN|PUSH_OVER_USER"
+if [ -z "${PUSHOVER_USER_KEY}" ] || [ -z "${PUSHOVER_API_TOKEN}" ]; then
+  echo "Required credentials <PUSHOVER_USER_KEY|PUSHOVER_API_TOKEN"
   exit 1
 fi
 
 curl -s \
-  -F "token=$PUSH_OVER_TOKEN" \
-  -F "user=$PUSH_OVER_USER" \
+  -F "user=$PUSHOVER_USER_KEY" \
+  -F "token=$PUSHOVER_API_TOKEN" \
   --form-string "message=[Monit] $MONIT_SERVICE - \
   $MONIT_DESCRIPTION" https://api.pushover.net/1/messages.json
 
-exit 0
+exit $?
